#!/usr/bin/env python3
"""
SubAgent role dispatcher (server-side).

Routes /subagent/<role> calls (and in-process SubAgentInvoker calls) to the
right swarm pipeline:

  - role="math"        → orchestrator with classification forced to MATHEMATICAL
  - role="engineer"    → run_engineer_mode bypassing the orchestrator
  - role="deep_search" → DeepSearchAgent.run

Every role:
  1. Sets SWARM_AS_SUBAGENT=1 so ReactSolver writes a sidechain JSONL.
  2. Acquires a process-wide semaphore so in-process callers obey
     MAX_CONCURRENT just like HTTP callers do.
  3. Pulls context_keys from AgentMemory and prepends as a "## Shared context"
     block so the subordinate sees the same facts.
  4. Joins on the worker thread with extra.timeout_s (default 1800, hard cap
     3600) and returns a 504-equivalent SubAgentResult on long-poll exceed.
  5. Writes a markdown deliverable to ~/.agent_bin/results/<topic>_<id>.md
     and publishes the path under swarm_<role>_<topic>_result via
     AgentMemory.set_context.
"""
from __future__ import annotations

import os
import re
import sys
import threading
import time
from typing import Any, Dict, List, Optional

from subagent import SubAgentResult  # type: ignore

# AgentMemory may not be available in some test contexts — guard the import
try:
    from agent_memory import get_default as _get_memory  # type: ignore
except Exception:
    _get_memory = None  # type: ignore

RESULTS_DIR = os.path.expanduser("~/.agent_bin/results")
os.makedirs(RESULTS_DIR, exist_ok=True)

# In-process semaphore so in-process callers obey MAX_CONCURRENT.
# Default 3 matches Config.MAX_CONCURRENT in swarm_api_server.py.
_MAX_CONCURRENT = int(os.getenv("MAX_CONCURRENT_JOBS", "3"))
_ROLE_SEMAPHORE = threading.Semaphore(_MAX_CONCURRENT)
_HARD_TIMEOUT_CAP = 3600

VALID_ROLES = {"math", "engineer", "deep_search"}


def _slug_topic(text: str, fallback: str) -> str:
    """Slugify the first 4-6 keywords of the task for the deliverable filename."""
    words = re.findall(r"[A-Za-z0-9]+", (text or "").lower())
    keywords = [w for w in words if len(w) > 2 and w not in {"the", "and", "for", "with", "from", "into"}]
    slug = "_".join(keywords[:5]) or fallback
    return slug[:60]


def write_deliverable_md(
    question: str,
    answer: str,
    job_id: str,
    role: str,
) -> str:
    """Write a markdown deliverable, return the absolute path."""
    os.makedirs(RESULTS_DIR, exist_ok=True)
    slug = _slug_topic(question, fallback=f"task_{job_id}")
    path = os.path.join(RESULTS_DIR, f"{slug}_{role}_{job_id}.md")
    body = (
        f"# {question.strip()[:200]}\n\n"
        f"_Generated by swarm.{role} (job `{job_id}`)._\n\n"
        f"---\n\n"
        f"{answer.strip() if answer else '*(no answer produced)*'}\n"
    )
    try:
        with open(path, "w") as f:
            f.write(body)
    except Exception as e:
        print(f"⚠️ write_deliverable_md failed: {e}")
        return ""
    return path


# ── Role workers ─────────────────────────────────────────────────────────────

def _build_bridged_task(task: str, context_keys: List[str]) -> str:
    if not context_keys or _get_memory is None:
        return task
    try:
        mem = _get_memory()
        lines: List[str] = []
        for k in context_keys:
            v = mem.get_context(k)
            if v is not None:
                lines.append(f"  {k}: {v}")
        if not lines:
            return task
        return (
            "## Shared context (from central board)\n"
            + "\n".join(lines)
            + "\n\n## Your task\n"
            + task
        )
    except Exception:
        return task


def _run_via_orchestrator(
    task: str,
    job_id: str,
    timeout_s: int,
) -> Dict[str, Any]:
    """Spawn a swarm worker thread that runs the standard orchestrator pipeline."""
    from swarm_api_server import _start_worker, job_manager, running_jobs, _rj_lock  # type: ignore

    job_manager.create_job(task)
    # Reuse the job_id that was created above (create_job returns its own id)
    real_job_id = list(job_manager.jobs.keys())[-1]
    thread = _start_worker(real_job_id, task)
    thread.join(timeout=timeout_s)
    if thread.is_alive():
        # long-poll exceeded
        return {
            "job_id": real_job_id,
            "status": "timeout",
            "answer": None,
            "elapsed": timeout_s,
        }
    job = job_manager.get_job(real_job_id) or {}
    return {
        "job_id": real_job_id,
        "status": job.get("status", "unknown"),
        "answer": job.get("answer"),
        "elapsed": job.get("elapsed", 0),
    }


def _run_engineer(task: str, job_id: str, timeout_s: int) -> Dict[str, Any]:
    """Bypass orchestrator; call run_engineer_mode directly."""
    try:
        from engineer_mode import run_engineer_mode  # type: ignore
    except Exception as e:
        return {"status": "failed", "answer": None, "error": f"engineer_mode unavailable: {e}"}

    import asyncio

    result_holder: Dict[str, Any] = {}

    def _runner() -> None:
        try:
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            try:
                # run_engineer_mode signature varies — call as kwargs for safety
                ans = loop.run_until_complete(run_engineer_mode(problem=task))
                result_holder["answer"] = ans
                result_holder["status"] = "completed"
            finally:
                loop.close()
        except Exception as e:
            result_holder["status"] = "failed"
            result_holder["answer"] = None
            result_holder["error"] = f"{type(e).__name__}: {e}"

    th = threading.Thread(target=_runner, daemon=True, name=f"swarm-engineer-{job_id}")
    th.start()
    th.join(timeout=timeout_s)
    if th.is_alive():
        return {"status": "timeout", "answer": None}
    return result_holder


def _run_deep_search(task: str, job_id: str, timeout_s: int) -> Dict[str, Any]:
    try:
        from deep_search_agent import DeepSearchAgent  # type: ignore
    except Exception as e:
        return {"status": "failed", "answer": None, "error": f"deep_search_agent unavailable: {e}"}

    import asyncio

    result_holder: Dict[str, Any] = {}

    def _runner() -> None:
        try:
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            try:
                agent = DeepSearchAgent()
                ans = loop.run_until_complete(agent.run(query=task, job_id=job_id))
                result_holder["answer"] = ans.get("answer", "") if isinstance(ans, dict) else str(ans)
                result_holder["deliverables"] = ans.get("deliverables", []) if isinstance(ans, dict) else []
                result_holder["status"] = "completed"
            finally:
                loop.close()
        except Exception as e:
            result_holder["status"] = "failed"
            result_holder["answer"] = None
            result_holder["error"] = f"{type(e).__name__}: {e}"

    th = threading.Thread(target=_runner, daemon=True, name=f"swarm-deepsearch-{job_id}")
    th.start()
    th.join(timeout=timeout_s)
    if th.is_alive():
        return {"status": "timeout", "answer": None}
    return result_holder


# ── Main entry ───────────────────────────────────────────────────────────────

def run_role_sync(
    role: str,
    task: str,
    *,
    max_iterations: int = 20,
    context_keys: Optional[List[str]] = None,
    extra: Optional[Dict[str, Any]] = None,
) -> SubAgentResult:
    role = (role or "").strip().lower()
    if role not in VALID_ROLES:
        return SubAgentResult(
            target=f"swarm:{role}",
            success=False,
            summary=f"Unknown role {role!r}. Valid: {sorted(VALID_ROLES)}",
            error="unknown_role",
        )
    if not task or not task.strip():
        return SubAgentResult(
            target=f"swarm:{role}",
            success=False,
            summary="task is required",
            error="empty_task",
        )

    extra = extra or {}
    timeout_s = int(extra.get("timeout_s", 1800))
    if timeout_s > _HARD_TIMEOUT_CAP:
        return SubAgentResult(
            target=f"swarm:{role}",
            success=False,
            summary=f"timeout_s exceeds {_HARD_TIMEOUT_CAP}s hard cap",
            error="timeout_cap_exceeded",
        )

    job_id = f"sub_{int(time.time())}_{os.getpid() & 0xffff:04x}"
    bridged = _build_bridged_task(task, context_keys or [])

    # Acquire concurrency slot. Block but do not deadlock — on timeout we bail.
    sem_ok = _ROLE_SEMAPHORE.acquire(timeout=timeout_s)
    if not sem_ok:
        return SubAgentResult(
            target=f"swarm:{role}",
            success=False,
            summary="Server busy — concurrency semaphore timeout",
            error="busy",
        )

    t0 = time.time()
    sidechain_dir = os.path.expanduser("~/.agent_bin/sidechains")
    os.makedirs(sidechain_dir, exist_ok=True)
    prev_flag = os.environ.get("SWARM_AS_SUBAGENT")
    os.environ["SWARM_AS_SUBAGENT"] = "1"
    try:
        if role == "math":
            outcome = _run_via_orchestrator(bridged, job_id, timeout_s)
        elif role == "engineer":
            outcome = _run_engineer(bridged, job_id, timeout_s)
        elif role == "deep_search":
            outcome = _run_deep_search(bridged, job_id, timeout_s)
        else:
            outcome = {"status": "failed", "answer": None, "error": "dispatch_missing"}
    finally:
        # restore env flag
        if prev_flag is None:
            os.environ.pop("SWARM_AS_SUBAGENT", None)
        else:
            os.environ["SWARM_AS_SUBAGENT"] = prev_flag
        _ROLE_SEMAPHORE.release()

    elapsed_ms = int((time.time() - t0) * 1000)
    status = outcome.get("status", "unknown")

    if status == "timeout":
        return SubAgentResult(
            target=f"swarm:{role}",
            success=False,
            summary=f"swarm:{role} long-poll timeout after {timeout_s}s",
            elapsed_ms=elapsed_ms,
            error="timeout",
        )
    if status not in ("completed", "succeeded"):
        return SubAgentResult(
            target=f"swarm:{role}",
            success=False,
            summary=f"swarm:{role} {status}: {outcome.get('error', '')}"[:4000],
            elapsed_ms=elapsed_ms,
            error=outcome.get("error") or status,
        )

    answer = outcome.get("answer") or ""
    deliverable_path = write_deliverable_md(
        question=task, answer=answer, job_id=job_id, role=role,
    )

    # Publish result to shared context board
    ctx_keys_written: List[str] = []
    slug = _slug_topic(task, fallback="result")
    key = f"swarm_{role}_{slug}_result"
    if _get_memory is not None and deliverable_path:
        try:
            mem = _get_memory(agent_id=f"swarm.{role}")
            ok = mem.set_context(key, deliverable_path, ttl=86400)
            if ok:
                ctx_keys_written.append(key)
        except Exception as e:
            print(f"⚠️ publish_context for {key} failed: {e}")

    extra_deliverables = outcome.get("deliverables") or []
    deliverables = [deliverable_path] + [p for p in extra_deliverables if p and p != deliverable_path]
    deliverables = [d for d in deliverables if d]

    # Locate sidechain (best effort: pick most recent file matching pattern)
    sidechain_path = ""
    try:
        candidates = [
            f for f in os.listdir(sidechain_dir)
            if f.startswith(f"swarm_{role}") or f.startswith(f"swarm_SP")
        ]
        candidates.sort(key=lambda f: os.path.getmtime(os.path.join(sidechain_dir, f)), reverse=True)
        if candidates:
            sidechain_path = os.path.join(sidechain_dir, candidates[0])
    except Exception:
        pass

    return SubAgentResult(
        target=f"swarm:{role}",
        success=True,
        summary=(answer[:300] + "…") if len(answer) > 300 else answer,
        deliverables=deliverables,
        context_keys_written=ctx_keys_written,
        sidechain_path=sidechain_path,
        elapsed_ms=elapsed_ms,
        iterations_used=int(outcome.get("iterations_used", 0)),
    )
