#!/usr/bin/env python3
"""
contract_test_template.py — emit pytest stubs from an ARCH.json contract.

Three files are generated inside {workspace}/tests/:
  - contract_routes.py      route existence + HTTP status
  - contract_models.py      model import + field presence
  - contract_happy_path.py  happy-path POST/PUT with response-shape validation

All generators are pure stdlib. If ARCH.json is sparse, the corresponding
block is skipped rather than emitting a failing stub.

Usage:
  from contract_test_template import emit_all
  emit_all(arch_dict, workspace="/home/u/app")
"""

from __future__ import annotations

import json
import os
import re
from typing import Any, Dict, List, Optional, Tuple


# --------------------------------------------------- payload generation --

_TYPE_DEFAULTS: Dict[str, Any] = {
    "str": "x",
    "string": "x",
    "int": 1,
    "integer": 1,
    "float": 1.0,
    "number": 1.0,
    "bool": True,
    "boolean": True,
    "email": "a@b.co",
    "emailstr": "a@b.co",
    "datetime": "2025-01-01T00:00:00Z",
    "date": "2025-01-01",
    "uuid": "00000000-0000-0000-0000-000000000000",
    "dict": {},
    "object": {},
    "list": [],
    "array": [],
    "none": None,
    "null": None,
}


def _default_for_type(type_str: str) -> Any:
    """Return a plausible default value for a declared Python/JSON type."""
    if not type_str:
        return "x"
    t = type_str.strip().lower()
    # List[T] / list[T]
    m = re.match(r"(?:list|array)\[(.+)\]$", t)
    if m:
        inner = m.group(1).strip()
        return [_default_for_type(inner)]
    # Optional[T]
    m = re.match(r"optional\[(.+)\]$", t)
    if m:
        return _default_for_type(m.group(1).strip())
    # Dict[K, V]
    if t.startswith("dict[") or t.startswith("object["):
        return {}
    return _TYPE_DEFAULTS.get(t, "x")


def _fields_from_schema(schema: Any) -> List[Tuple[str, str]]:
    """Normalize a request/response_schema into [(name, type), ...].

    Accepts:
      - str: name of a Pydantic model referenced in ARCH.models
      - dict: {field: type, ...} OR {"fields": [{"name","type"}]}
      - list of {"name","type"}
      - None: returns []
    """
    if not schema:
        return []
    if isinstance(schema, list):
        out = []
        for entry in schema:
            if isinstance(entry, dict):
                out.append((str(entry.get("name", "")), str(entry.get("type", "str"))))
        return [(n, t) for n, t in out if n]
    if isinstance(schema, dict):
        if "fields" in schema and isinstance(schema["fields"], list):
            return _fields_from_schema(schema["fields"])
        # Treat flat dict as {name: type}
        return [(str(k), str(v)) for k, v in schema.items() if k]
    return []


def _resolve_schema_ref(schema: Any, models: List[Dict]) -> List[Tuple[str, str]]:
    """If schema is a string model name, look it up in ARCH.models and return fields."""
    if isinstance(schema, str) and schema:
        for m in models:
            if m.get("name") == schema:
                return _fields_from_schema(m.get("fields"))
        return []
    return _fields_from_schema(schema)


def _generate_payload(fields: List[Tuple[str, str]]) -> Dict[str, Any]:
    """Build a minimal valid JSON payload from typed field list."""
    return {name: _default_for_type(typ) for name, typ in fields if name}


# -------------------------------------------------------- file emitters --


def _header() -> str:
    return (
        "# Auto-generated by contract_test_template.\n"
        "# DO NOT EDIT BY HAND — regenerated from ARCH.json each tester gate.\n"
        "import json\n"
        "import pytest\n"
    )


def _try_import_app() -> str:
    """Snippet that tries several common entrypoints for the FastAPI/Flask app."""
    return (
        "def _load_app():\n"
        "    errors = []\n"
        "    for mod_name in ('app.main', 'main', 'app', 'server', 'api.main'):\n"
        "        try:\n"
        "            import importlib\n"
        "            m = importlib.import_module(mod_name)\n"
        "            for attr in ('app', 'application', 'api'):\n"
        "                a = getattr(m, attr, None)\n"
        "                if a is not None:\n"
        "                    return a\n"
        "        except Exception as e:\n"
        "            errors.append(f'{mod_name}: {e}')\n"
        "    pytest.skip('app not importable: ' + ' | '.join(errors[:3]))\n"
    )


def emit_routes(arch: Dict[str, Any]) -> str:
    """Emit tests/contract_routes.py content."""
    routes = arch.get("routes") or []
    lines = [_header()]
    lines.append("from fastapi.testclient import TestClient  # type: ignore\n")
    lines.append(_try_import_app())
    lines.append("\n@pytest.fixture(scope='module')\ndef client():\n"
                 "    app = _load_app()\n"
                 "    return TestClient(app)\n\n")
    if not routes:
        lines.append("def test_routes_declared():\n    pytest.skip('no routes declared in ARCH')\n")
        return "".join(lines)
    for i, r in enumerate(routes):
        method = (r.get("method") or "GET").upper()
        path = r.get("path") or "/"
        safe_name = re.sub(r"[^a-zA-Z0-9_]+", "_", f"{method}_{path}").strip("_")[:60] or f"route_{i}"
        lines.append(
            f"def test_route_{i}_{safe_name}(client):\n"
            f"    r = client.request({method!r}, {path!r})\n"
            f"    assert r.status_code < 500, f'5xx from declared route: {{r.status_code}} {{r.text[:200]}}'\n\n"
        )
    return "".join(lines)


def emit_models(arch: Dict[str, Any]) -> str:
    """Emit tests/contract_models.py content — imports declared models and checks field presence."""
    models = arch.get("models") or []
    lines = [_header()]
    if not models:
        lines.append("def test_models_declared():\n    pytest.skip('no models declared in ARCH')\n")
        return "".join(lines)

    lines.append(
        "def _find_model(name):\n"
        "    import importlib\n"
        "    for mod in ('app.models', 'models', 'app.db.models', 'db.models', 'schemas', 'app.schemas'):\n"
        "        try:\n"
        "            m = importlib.import_module(mod)\n"
        "            cls = getattr(m, name, None)\n"
        "            if cls is not None:\n"
        "                return cls\n"
        "        except Exception:\n"
        "            continue\n"
        "    return None\n\n"
    )
    for i, m in enumerate(models):
        name = m.get("name") or f"Model{i}"
        fields = _fields_from_schema(m.get("fields"))
        field_names = [n for n, _ in fields]
        safe = re.sub(r"[^a-zA-Z0-9_]+", "_", name)
        lines.append(
            f"def test_model_{i}_{safe}_exists():\n"
            f"    cls = _find_model({name!r})\n"
            f"    assert cls is not None, 'Model {name} not importable'\n"
        )
        if field_names:
            lines.append(
                f"    # Check declared fields are present (SQLAlchemy columns OR Pydantic fields)\n"
                f"    declared = {field_names!r}\n"
                f"    available = set()\n"
                f"    if hasattr(cls, '__table__'):\n"
                f"        available |= {{c.name for c in cls.__table__.columns}}\n"
                f"    if hasattr(cls, 'model_fields'):\n"
                f"        available |= set(cls.model_fields.keys())\n"
                f"    if hasattr(cls, '__fields__'):\n"
                f"        available |= set(cls.__fields__.keys())\n"
                f"    missing = [f for f in declared if f not in available]\n"
                f"    assert not missing, f'{name} missing fields: {{missing}} (have: {{available}})'\n\n"
            )
        else:
            lines.append("\n")
    return "".join(lines)


def emit_happy_path(arch: Dict[str, Any]) -> str:
    """Emit tests/contract_happy_path.py — minimal payload POST/PUT/PATCH + response-shape check."""
    routes = arch.get("routes") or []
    models = arch.get("models") or []
    lines = [_header()]
    lines.append("from fastapi.testclient import TestClient  # type: ignore\n")
    lines.append(_try_import_app())
    lines.append("\n@pytest.fixture(scope='module')\ndef client():\n"
                 "    app = _load_app()\n"
                 "    return TestClient(app)\n\n")

    emitted = 0
    for i, r in enumerate(routes):
        method = (r.get("method") or "GET").upper()
        path = r.get("path") or "/"
        req_schema = r.get("request_schema")
        resp_schema = r.get("response_schema")
        req_fields = _resolve_schema_ref(req_schema, models) if req_schema else []
        resp_fields = _resolve_schema_ref(resp_schema, models) if resp_schema else []

        if method not in ("POST", "PUT", "PATCH") and not resp_fields:
            # GET without declared response shape — skip
            continue
        if method in ("POST", "PUT", "PATCH") and not req_fields:
            continue

        payload = _generate_payload(req_fields) if req_fields else {}
        safe_name = re.sub(r"[^a-zA-Z0-9_]+", "_", f"{method}_{path}").strip("_")[:60] or f"route_{i}"
        # Substitute simple path params like /users/{id} with a default
        concrete_path = re.sub(r"\{[^/}]+\}", "1", path)

        if method in ("POST", "PUT", "PATCH"):
            lines.append(
                f"def test_happy_{i}_{safe_name}(client):\n"
                f"    payload = {payload!r}\n"
                f"    r = client.request({method!r}, {concrete_path!r}, json=payload)\n"
                f"    assert r.status_code < 400 or r.status_code == 422, (\n"
                f"        f'unexpected status {{r.status_code}}: {{r.text[:300]}}'\n"
                f"    )\n"
            )
        else:
            lines.append(
                f"def test_happy_{i}_{safe_name}(client):\n"
                f"    r = client.request({method!r}, {concrete_path!r})\n"
                f"    assert r.status_code < 500, f'5xx: {{r.status_code}} {{r.text[:200]}}'\n"
            )

        # Response-shape validation
        if resp_fields and method in ("GET", "POST", "PUT", "PATCH"):
            resp_field_names = [n for n, _ in resp_fields]
            lines.append(
                f"    if 200 <= r.status_code < 300 and r.headers.get('content-type', '').startswith('application/json'):\n"
                f"        try:\n"
                f"            body = r.json()\n"
                f"        except Exception:\n"
                f"            body = None\n"
                f"        if isinstance(body, dict):\n"
                f"            declared = {resp_field_names!r}\n"
                f"            missing = [f for f in declared if f not in body]\n"
                f"            assert not missing, f'response missing declared fields: {{missing}}'\n"
            )
        lines.append("\n")
        emitted += 1

    if emitted == 0:
        lines.append("def test_happy_path_declared():\n"
                     "    pytest.skip('no routes with both request_schema and response_schema declared')\n")
    return "".join(lines)


# ------------------------------------------------------------- driver --


def emit_all(arch: Dict[str, Any], workspace: str) -> Dict[str, str]:
    """Write the 3 test files under {workspace}/tests/. Returns {name: path} map."""
    if not isinstance(arch, dict):
        return {}
    tests_dir = os.path.join(os.path.expanduser(workspace), "tests")
    os.makedirs(tests_dir, exist_ok=True)

    # Ensure tests/ is a package
    init_path = os.path.join(tests_dir, "__init__.py")
    if not os.path.exists(init_path):
        with open(init_path, "w") as f:
            f.write("")

    outputs = {
        "routes": os.path.join(tests_dir, "contract_routes.py"),
        "models": os.path.join(tests_dir, "contract_models.py"),
        "happy_path": os.path.join(tests_dir, "contract_happy_path.py"),
    }
    with open(outputs["routes"], "w") as f:
        f.write(emit_routes(arch))
    with open(outputs["models"], "w") as f:
        f.write(emit_models(arch))
    with open(outputs["happy_path"], "w") as f:
        f.write(emit_happy_path(arch))
    return outputs


# ----------------------------------------------------------------- CLI --

if __name__ == "__main__":
    import sys
    if len(sys.argv) < 3:
        print("usage: contract_test_template.py <ARCH.json> <workspace>")
        sys.exit(1)
    with open(sys.argv[1]) as f:
        arch = json.load(f)
    out = emit_all(arch, sys.argv[2])
    print("Emitted:")
    for k, v in out.items():
        print(f"  {k}: {v}")
